import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

const Main = styled.main`
  width: 100%;
  background-color: #0093E9;
background-image: linear-gradient(160deg, #0093E9 0%, #80D0C7 100%);
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
`;
const Heading = styled.h1`
  font-size: 5rem;
  color:#fff;
  font-weight:lighter;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Heading>Next.js Website</Heading>
      </Main>
      {/* <Image src="/vercel.svg" layout="fill" /> */}
    </div>
  );
}

